/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "scheduler_constants.h"



const schedulerConstants g_scheduler_constants;

schedulerConstants::schedulerConstants() {
}



