/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Scheduler_H
#define Scheduler_H

#include <thrift/TDispatchProcessor.h>
#include "scheduler_types.h"



class SchedulerIf {
 public:
  virtual ~SchedulerIf() {}
  virtual int64_t Submit(const TaskInfo& task_info) = 0;
  virtual void Query(TaskInfo& _return, const int64_t task_id) = 0;
  virtual int32_t RemoveTask(const int64_t task_id) = 0;
  virtual int32_t TaskStarted(const int64_t task_id, const bool status) = 0;
  virtual int32_t TaskFinished(const int64_t task_id, const bool status) = 0;
  virtual int32_t AddFramework(const FrameworkInfo& framework_info) = 0;
  virtual bool DeleteFramework(const std::string& name) = 0;
  virtual int32_t AddExecutor(const std::string& name) = 0;
  virtual int32_t DeleteExecutor(const int64_t executor_id) = 0;
};

class SchedulerIfFactory {
 public:
  typedef SchedulerIf Handler;

  virtual ~SchedulerIfFactory() {}

  virtual SchedulerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SchedulerIf* /* handler */) = 0;
};

class SchedulerIfSingletonFactory : virtual public SchedulerIfFactory {
 public:
  SchedulerIfSingletonFactory(const boost::shared_ptr<SchedulerIf>& iface) : iface_(iface) {}
  virtual ~SchedulerIfSingletonFactory() {}

  virtual SchedulerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(SchedulerIf* /* handler */) {}

 protected:
  boost::shared_ptr<SchedulerIf> iface_;
};

class SchedulerNull : virtual public SchedulerIf {
 public:
  virtual ~SchedulerNull() {}
  int64_t Submit(const TaskInfo& /* task_info */) {
    int64_t _return = 0;
    return _return;
  }
  void Query(TaskInfo& /* _return */, const int64_t /* task_id */) {
    return;
  }
  int32_t RemoveTask(const int64_t /* task_id */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t TaskStarted(const int64_t /* task_id */, const bool /* status */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t TaskFinished(const int64_t /* task_id */, const bool /* status */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t AddFramework(const FrameworkInfo& /* framework_info */) {
    int32_t _return = 0;
    return _return;
  }
  bool DeleteFramework(const std::string& /* name */) {
    bool _return = false;
    return _return;
  }
  int32_t AddExecutor(const std::string& /* name */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t DeleteExecutor(const int64_t /* executor_id */) {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _Scheduler_Submit_args__isset {
  _Scheduler_Submit_args__isset() : task_info(false) {}
  bool task_info;
} _Scheduler_Submit_args__isset;

class Scheduler_Submit_args {
 public:

  Scheduler_Submit_args() {
  }

  virtual ~Scheduler_Submit_args() throw() {}

  TaskInfo task_info;

  _Scheduler_Submit_args__isset __isset;

  void __set_task_info(const TaskInfo& val) {
    task_info = val;
  }

  bool operator == (const Scheduler_Submit_args & rhs) const
  {
    if (!(task_info == rhs.task_info))
      return false;
    return true;
  }
  bool operator != (const Scheduler_Submit_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_Submit_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_Submit_pargs {
 public:


  virtual ~Scheduler_Submit_pargs() throw() {}

  const TaskInfo* task_info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_Submit_result__isset {
  _Scheduler_Submit_result__isset() : success(false) {}
  bool success;
} _Scheduler_Submit_result__isset;

class Scheduler_Submit_result {
 public:

  Scheduler_Submit_result() : success(0) {
  }

  virtual ~Scheduler_Submit_result() throw() {}

  int64_t success;

  _Scheduler_Submit_result__isset __isset;

  void __set_success(const int64_t val) {
    success = val;
  }

  bool operator == (const Scheduler_Submit_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_Submit_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_Submit_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_Submit_presult__isset {
  _Scheduler_Submit_presult__isset() : success(false) {}
  bool success;
} _Scheduler_Submit_presult__isset;

class Scheduler_Submit_presult {
 public:


  virtual ~Scheduler_Submit_presult() throw() {}

  int64_t* success;

  _Scheduler_Submit_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_Query_args__isset {
  _Scheduler_Query_args__isset() : task_id(false) {}
  bool task_id;
} _Scheduler_Query_args__isset;

class Scheduler_Query_args {
 public:

  Scheduler_Query_args() : task_id(0) {
  }

  virtual ~Scheduler_Query_args() throw() {}

  int64_t task_id;

  _Scheduler_Query_args__isset __isset;

  void __set_task_id(const int64_t val) {
    task_id = val;
  }

  bool operator == (const Scheduler_Query_args & rhs) const
  {
    if (!(task_id == rhs.task_id))
      return false;
    return true;
  }
  bool operator != (const Scheduler_Query_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_Query_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_Query_pargs {
 public:


  virtual ~Scheduler_Query_pargs() throw() {}

  const int64_t* task_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_Query_result__isset {
  _Scheduler_Query_result__isset() : success(false) {}
  bool success;
} _Scheduler_Query_result__isset;

class Scheduler_Query_result {
 public:

  Scheduler_Query_result() {
  }

  virtual ~Scheduler_Query_result() throw() {}

  TaskInfo success;

  _Scheduler_Query_result__isset __isset;

  void __set_success(const TaskInfo& val) {
    success = val;
  }

  bool operator == (const Scheduler_Query_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_Query_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_Query_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_Query_presult__isset {
  _Scheduler_Query_presult__isset() : success(false) {}
  bool success;
} _Scheduler_Query_presult__isset;

class Scheduler_Query_presult {
 public:


  virtual ~Scheduler_Query_presult() throw() {}

  TaskInfo* success;

  _Scheduler_Query_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_RemoveTask_args__isset {
  _Scheduler_RemoveTask_args__isset() : task_id(false) {}
  bool task_id;
} _Scheduler_RemoveTask_args__isset;

class Scheduler_RemoveTask_args {
 public:

  Scheduler_RemoveTask_args() : task_id(0) {
  }

  virtual ~Scheduler_RemoveTask_args() throw() {}

  int64_t task_id;

  _Scheduler_RemoveTask_args__isset __isset;

  void __set_task_id(const int64_t val) {
    task_id = val;
  }

  bool operator == (const Scheduler_RemoveTask_args & rhs) const
  {
    if (!(task_id == rhs.task_id))
      return false;
    return true;
  }
  bool operator != (const Scheduler_RemoveTask_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_RemoveTask_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_RemoveTask_pargs {
 public:


  virtual ~Scheduler_RemoveTask_pargs() throw() {}

  const int64_t* task_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_RemoveTask_result__isset {
  _Scheduler_RemoveTask_result__isset() : success(false) {}
  bool success;
} _Scheduler_RemoveTask_result__isset;

class Scheduler_RemoveTask_result {
 public:

  Scheduler_RemoveTask_result() : success(0) {
  }

  virtual ~Scheduler_RemoveTask_result() throw() {}

  int32_t success;

  _Scheduler_RemoveTask_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Scheduler_RemoveTask_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_RemoveTask_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_RemoveTask_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_RemoveTask_presult__isset {
  _Scheduler_RemoveTask_presult__isset() : success(false) {}
  bool success;
} _Scheduler_RemoveTask_presult__isset;

class Scheduler_RemoveTask_presult {
 public:


  virtual ~Scheduler_RemoveTask_presult() throw() {}

  int32_t* success;

  _Scheduler_RemoveTask_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_TaskStarted_args__isset {
  _Scheduler_TaskStarted_args__isset() : task_id(false), status(false) {}
  bool task_id;
  bool status;
} _Scheduler_TaskStarted_args__isset;

class Scheduler_TaskStarted_args {
 public:

  Scheduler_TaskStarted_args() : task_id(0), status(0) {
  }

  virtual ~Scheduler_TaskStarted_args() throw() {}

  int64_t task_id;
  bool status;

  _Scheduler_TaskStarted_args__isset __isset;

  void __set_task_id(const int64_t val) {
    task_id = val;
  }

  void __set_status(const bool val) {
    status = val;
  }

  bool operator == (const Scheduler_TaskStarted_args & rhs) const
  {
    if (!(task_id == rhs.task_id))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const Scheduler_TaskStarted_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_TaskStarted_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_TaskStarted_pargs {
 public:


  virtual ~Scheduler_TaskStarted_pargs() throw() {}

  const int64_t* task_id;
  const bool* status;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_TaskStarted_result__isset {
  _Scheduler_TaskStarted_result__isset() : success(false) {}
  bool success;
} _Scheduler_TaskStarted_result__isset;

class Scheduler_TaskStarted_result {
 public:

  Scheduler_TaskStarted_result() : success(0) {
  }

  virtual ~Scheduler_TaskStarted_result() throw() {}

  int32_t success;

  _Scheduler_TaskStarted_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Scheduler_TaskStarted_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_TaskStarted_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_TaskStarted_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_TaskStarted_presult__isset {
  _Scheduler_TaskStarted_presult__isset() : success(false) {}
  bool success;
} _Scheduler_TaskStarted_presult__isset;

class Scheduler_TaskStarted_presult {
 public:


  virtual ~Scheduler_TaskStarted_presult() throw() {}

  int32_t* success;

  _Scheduler_TaskStarted_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_TaskFinished_args__isset {
  _Scheduler_TaskFinished_args__isset() : task_id(false), status(false) {}
  bool task_id;
  bool status;
} _Scheduler_TaskFinished_args__isset;

class Scheduler_TaskFinished_args {
 public:

  Scheduler_TaskFinished_args() : task_id(0), status(0) {
  }

  virtual ~Scheduler_TaskFinished_args() throw() {}

  int64_t task_id;
  bool status;

  _Scheduler_TaskFinished_args__isset __isset;

  void __set_task_id(const int64_t val) {
    task_id = val;
  }

  void __set_status(const bool val) {
    status = val;
  }

  bool operator == (const Scheduler_TaskFinished_args & rhs) const
  {
    if (!(task_id == rhs.task_id))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const Scheduler_TaskFinished_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_TaskFinished_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_TaskFinished_pargs {
 public:


  virtual ~Scheduler_TaskFinished_pargs() throw() {}

  const int64_t* task_id;
  const bool* status;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_TaskFinished_result__isset {
  _Scheduler_TaskFinished_result__isset() : success(false) {}
  bool success;
} _Scheduler_TaskFinished_result__isset;

class Scheduler_TaskFinished_result {
 public:

  Scheduler_TaskFinished_result() : success(0) {
  }

  virtual ~Scheduler_TaskFinished_result() throw() {}

  int32_t success;

  _Scheduler_TaskFinished_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Scheduler_TaskFinished_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_TaskFinished_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_TaskFinished_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_TaskFinished_presult__isset {
  _Scheduler_TaskFinished_presult__isset() : success(false) {}
  bool success;
} _Scheduler_TaskFinished_presult__isset;

class Scheduler_TaskFinished_presult {
 public:


  virtual ~Scheduler_TaskFinished_presult() throw() {}

  int32_t* success;

  _Scheduler_TaskFinished_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_AddFramework_args__isset {
  _Scheduler_AddFramework_args__isset() : framework_info(false) {}
  bool framework_info;
} _Scheduler_AddFramework_args__isset;

class Scheduler_AddFramework_args {
 public:

  Scheduler_AddFramework_args() {
  }

  virtual ~Scheduler_AddFramework_args() throw() {}

  FrameworkInfo framework_info;

  _Scheduler_AddFramework_args__isset __isset;

  void __set_framework_info(const FrameworkInfo& val) {
    framework_info = val;
  }

  bool operator == (const Scheduler_AddFramework_args & rhs) const
  {
    if (!(framework_info == rhs.framework_info))
      return false;
    return true;
  }
  bool operator != (const Scheduler_AddFramework_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_AddFramework_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_AddFramework_pargs {
 public:


  virtual ~Scheduler_AddFramework_pargs() throw() {}

  const FrameworkInfo* framework_info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_AddFramework_result__isset {
  _Scheduler_AddFramework_result__isset() : success(false) {}
  bool success;
} _Scheduler_AddFramework_result__isset;

class Scheduler_AddFramework_result {
 public:

  Scheduler_AddFramework_result() : success(0) {
  }

  virtual ~Scheduler_AddFramework_result() throw() {}

  int32_t success;

  _Scheduler_AddFramework_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Scheduler_AddFramework_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_AddFramework_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_AddFramework_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_AddFramework_presult__isset {
  _Scheduler_AddFramework_presult__isset() : success(false) {}
  bool success;
} _Scheduler_AddFramework_presult__isset;

class Scheduler_AddFramework_presult {
 public:


  virtual ~Scheduler_AddFramework_presult() throw() {}

  int32_t* success;

  _Scheduler_AddFramework_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_DeleteFramework_args__isset {
  _Scheduler_DeleteFramework_args__isset() : name(false) {}
  bool name;
} _Scheduler_DeleteFramework_args__isset;

class Scheduler_DeleteFramework_args {
 public:

  Scheduler_DeleteFramework_args() : name() {
  }

  virtual ~Scheduler_DeleteFramework_args() throw() {}

  std::string name;

  _Scheduler_DeleteFramework_args__isset __isset;

  void __set_name(const std::string& val) {
    name = val;
  }

  bool operator == (const Scheduler_DeleteFramework_args & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const Scheduler_DeleteFramework_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_DeleteFramework_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_DeleteFramework_pargs {
 public:


  virtual ~Scheduler_DeleteFramework_pargs() throw() {}

  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_DeleteFramework_result__isset {
  _Scheduler_DeleteFramework_result__isset() : success(false) {}
  bool success;
} _Scheduler_DeleteFramework_result__isset;

class Scheduler_DeleteFramework_result {
 public:

  Scheduler_DeleteFramework_result() : success(0) {
  }

  virtual ~Scheduler_DeleteFramework_result() throw() {}

  bool success;

  _Scheduler_DeleteFramework_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const Scheduler_DeleteFramework_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_DeleteFramework_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_DeleteFramework_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_DeleteFramework_presult__isset {
  _Scheduler_DeleteFramework_presult__isset() : success(false) {}
  bool success;
} _Scheduler_DeleteFramework_presult__isset;

class Scheduler_DeleteFramework_presult {
 public:


  virtual ~Scheduler_DeleteFramework_presult() throw() {}

  bool* success;

  _Scheduler_DeleteFramework_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_AddExecutor_args__isset {
  _Scheduler_AddExecutor_args__isset() : name(false) {}
  bool name;
} _Scheduler_AddExecutor_args__isset;

class Scheduler_AddExecutor_args {
 public:

  Scheduler_AddExecutor_args() : name() {
  }

  virtual ~Scheduler_AddExecutor_args() throw() {}

  std::string name;

  _Scheduler_AddExecutor_args__isset __isset;

  void __set_name(const std::string& val) {
    name = val;
  }

  bool operator == (const Scheduler_AddExecutor_args & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const Scheduler_AddExecutor_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_AddExecutor_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_AddExecutor_pargs {
 public:


  virtual ~Scheduler_AddExecutor_pargs() throw() {}

  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_AddExecutor_result__isset {
  _Scheduler_AddExecutor_result__isset() : success(false) {}
  bool success;
} _Scheduler_AddExecutor_result__isset;

class Scheduler_AddExecutor_result {
 public:

  Scheduler_AddExecutor_result() : success(0) {
  }

  virtual ~Scheduler_AddExecutor_result() throw() {}

  int32_t success;

  _Scheduler_AddExecutor_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Scheduler_AddExecutor_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_AddExecutor_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_AddExecutor_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_AddExecutor_presult__isset {
  _Scheduler_AddExecutor_presult__isset() : success(false) {}
  bool success;
} _Scheduler_AddExecutor_presult__isset;

class Scheduler_AddExecutor_presult {
 public:


  virtual ~Scheduler_AddExecutor_presult() throw() {}

  int32_t* success;

  _Scheduler_AddExecutor_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Scheduler_DeleteExecutor_args__isset {
  _Scheduler_DeleteExecutor_args__isset() : executor_id(false) {}
  bool executor_id;
} _Scheduler_DeleteExecutor_args__isset;

class Scheduler_DeleteExecutor_args {
 public:

  Scheduler_DeleteExecutor_args() : executor_id(0) {
  }

  virtual ~Scheduler_DeleteExecutor_args() throw() {}

  int64_t executor_id;

  _Scheduler_DeleteExecutor_args__isset __isset;

  void __set_executor_id(const int64_t val) {
    executor_id = val;
  }

  bool operator == (const Scheduler_DeleteExecutor_args & rhs) const
  {
    if (!(executor_id == rhs.executor_id))
      return false;
    return true;
  }
  bool operator != (const Scheduler_DeleteExecutor_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_DeleteExecutor_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Scheduler_DeleteExecutor_pargs {
 public:


  virtual ~Scheduler_DeleteExecutor_pargs() throw() {}

  const int64_t* executor_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_DeleteExecutor_result__isset {
  _Scheduler_DeleteExecutor_result__isset() : success(false) {}
  bool success;
} _Scheduler_DeleteExecutor_result__isset;

class Scheduler_DeleteExecutor_result {
 public:

  Scheduler_DeleteExecutor_result() : success(0) {
  }

  virtual ~Scheduler_DeleteExecutor_result() throw() {}

  int32_t success;

  _Scheduler_DeleteExecutor_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Scheduler_DeleteExecutor_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Scheduler_DeleteExecutor_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Scheduler_DeleteExecutor_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Scheduler_DeleteExecutor_presult__isset {
  _Scheduler_DeleteExecutor_presult__isset() : success(false) {}
  bool success;
} _Scheduler_DeleteExecutor_presult__isset;

class Scheduler_DeleteExecutor_presult {
 public:


  virtual ~Scheduler_DeleteExecutor_presult() throw() {}

  int32_t* success;

  _Scheduler_DeleteExecutor_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class SchedulerClient : virtual public SchedulerIf {
 public:
  SchedulerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  SchedulerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int64_t Submit(const TaskInfo& task_info);
  void send_Submit(const TaskInfo& task_info);
  int64_t recv_Submit();
  void Query(TaskInfo& _return, const int64_t task_id);
  void send_Query(const int64_t task_id);
  void recv_Query(TaskInfo& _return);
  int32_t RemoveTask(const int64_t task_id);
  void send_RemoveTask(const int64_t task_id);
  int32_t recv_RemoveTask();
  int32_t TaskStarted(const int64_t task_id, const bool status);
  void send_TaskStarted(const int64_t task_id, const bool status);
  int32_t recv_TaskStarted();
  int32_t TaskFinished(const int64_t task_id, const bool status);
  void send_TaskFinished(const int64_t task_id, const bool status);
  int32_t recv_TaskFinished();
  int32_t AddFramework(const FrameworkInfo& framework_info);
  void send_AddFramework(const FrameworkInfo& framework_info);
  int32_t recv_AddFramework();
  bool DeleteFramework(const std::string& name);
  void send_DeleteFramework(const std::string& name);
  bool recv_DeleteFramework();
  int32_t AddExecutor(const std::string& name);
  void send_AddExecutor(const std::string& name);
  int32_t recv_AddExecutor();
  int32_t DeleteExecutor(const int64_t executor_id);
  void send_DeleteExecutor(const int64_t executor_id);
  int32_t recv_DeleteExecutor();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SchedulerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<SchedulerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (SchedulerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Submit(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Query(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveTask(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_TaskStarted(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_TaskFinished(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_AddFramework(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_DeleteFramework(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_AddExecutor(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_DeleteExecutor(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SchedulerProcessor(boost::shared_ptr<SchedulerIf> iface) :
    iface_(iface) {
    processMap_["Submit"] = &SchedulerProcessor::process_Submit;
    processMap_["Query"] = &SchedulerProcessor::process_Query;
    processMap_["RemoveTask"] = &SchedulerProcessor::process_RemoveTask;
    processMap_["TaskStarted"] = &SchedulerProcessor::process_TaskStarted;
    processMap_["TaskFinished"] = &SchedulerProcessor::process_TaskFinished;
    processMap_["AddFramework"] = &SchedulerProcessor::process_AddFramework;
    processMap_["DeleteFramework"] = &SchedulerProcessor::process_DeleteFramework;
    processMap_["AddExecutor"] = &SchedulerProcessor::process_AddExecutor;
    processMap_["DeleteExecutor"] = &SchedulerProcessor::process_DeleteExecutor;
  }

  virtual ~SchedulerProcessor() {}
};

class SchedulerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SchedulerProcessorFactory(const ::boost::shared_ptr< SchedulerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< SchedulerIfFactory > handlerFactory_;
};

class SchedulerMultiface : virtual public SchedulerIf {
 public:
  SchedulerMultiface(std::vector<boost::shared_ptr<SchedulerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SchedulerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<SchedulerIf> > ifaces_;
  SchedulerMultiface() {}
  void add(boost::shared_ptr<SchedulerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int64_t Submit(const TaskInfo& task_info) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Submit(task_info);
    }
    return ifaces_[i]->Submit(task_info);
  }

  void Query(TaskInfo& _return, const int64_t task_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Query(_return, task_id);
    }
    ifaces_[i]->Query(_return, task_id);
    return;
  }

  int32_t RemoveTask(const int64_t task_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveTask(task_id);
    }
    return ifaces_[i]->RemoveTask(task_id);
  }

  int32_t TaskStarted(const int64_t task_id, const bool status) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->TaskStarted(task_id, status);
    }
    return ifaces_[i]->TaskStarted(task_id, status);
  }

  int32_t TaskFinished(const int64_t task_id, const bool status) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->TaskFinished(task_id, status);
    }
    return ifaces_[i]->TaskFinished(task_id, status);
  }

  int32_t AddFramework(const FrameworkInfo& framework_info) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddFramework(framework_info);
    }
    return ifaces_[i]->AddFramework(framework_info);
  }

  bool DeleteFramework(const std::string& name) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->DeleteFramework(name);
    }
    return ifaces_[i]->DeleteFramework(name);
  }

  int32_t AddExecutor(const std::string& name) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddExecutor(name);
    }
    return ifaces_[i]->AddExecutor(name);
  }

  int32_t DeleteExecutor(const int64_t executor_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->DeleteExecutor(executor_id);
    }
    return ifaces_[i]->DeleteExecutor(executor_id);
  }

};



#endif
