/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "collector_constants.h"



const collectorConstants g_collector_constants;

collectorConstants::collectorConstants() {
}



