/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Collector_H
#define Collector_H

#include <thrift/TDispatchProcessor.h>
#include "collector_types.h"



class CollectorIf {
 public:
  virtual ~CollectorIf() {}
  virtual void Match(std::string& _return, const std::string& str_ad) = 0;
  virtual void Heartbeat(const MachineInfo& info) = 0;
};

class CollectorIfFactory {
 public:
  typedef CollectorIf Handler;

  virtual ~CollectorIfFactory() {}

  virtual CollectorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CollectorIf* /* handler */) = 0;
};

class CollectorIfSingletonFactory : virtual public CollectorIfFactory {
 public:
  CollectorIfSingletonFactory(const boost::shared_ptr<CollectorIf>& iface) : iface_(iface) {}
  virtual ~CollectorIfSingletonFactory() {}

  virtual CollectorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(CollectorIf* /* handler */) {}

 protected:
  boost::shared_ptr<CollectorIf> iface_;
};

class CollectorNull : virtual public CollectorIf {
 public:
  virtual ~CollectorNull() {}
  void Match(std::string& /* _return */, const std::string& /* str_ad */) {
    return;
  }
  void Heartbeat(const MachineInfo& /* info */) {
    return;
  }
};

typedef struct _Collector_Match_args__isset {
  _Collector_Match_args__isset() : str_ad(false) {}
  bool str_ad;
} _Collector_Match_args__isset;

class Collector_Match_args {
 public:

  Collector_Match_args() : str_ad() {
  }

  virtual ~Collector_Match_args() throw() {}

  std::string str_ad;

  _Collector_Match_args__isset __isset;

  void __set_str_ad(const std::string& val) {
    str_ad = val;
  }

  bool operator == (const Collector_Match_args & rhs) const
  {
    if (!(str_ad == rhs.str_ad))
      return false;
    return true;
  }
  bool operator != (const Collector_Match_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_Match_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_Match_pargs {
 public:


  virtual ~Collector_Match_pargs() throw() {}

  const std::string* str_ad;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_Match_result__isset {
  _Collector_Match_result__isset() : success(false) {}
  bool success;
} _Collector_Match_result__isset;

class Collector_Match_result {
 public:

  Collector_Match_result() : success() {
  }

  virtual ~Collector_Match_result() throw() {}

  std::string success;

  _Collector_Match_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const Collector_Match_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Collector_Match_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_Match_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_Match_presult__isset {
  _Collector_Match_presult__isset() : success(false) {}
  bool success;
} _Collector_Match_presult__isset;

class Collector_Match_presult {
 public:


  virtual ~Collector_Match_presult() throw() {}

  std::string* success;

  _Collector_Match_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Collector_Heartbeat_args__isset {
  _Collector_Heartbeat_args__isset() : info(false) {}
  bool info;
} _Collector_Heartbeat_args__isset;

class Collector_Heartbeat_args {
 public:

  Collector_Heartbeat_args() {
  }

  virtual ~Collector_Heartbeat_args() throw() {}

  MachineInfo info;

  _Collector_Heartbeat_args__isset __isset;

  void __set_info(const MachineInfo& val) {
    info = val;
  }

  bool operator == (const Collector_Heartbeat_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const Collector_Heartbeat_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_Heartbeat_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_Heartbeat_pargs {
 public:


  virtual ~Collector_Heartbeat_pargs() throw() {}

  const MachineInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_Heartbeat_result {
 public:

  Collector_Heartbeat_result() {
  }

  virtual ~Collector_Heartbeat_result() throw() {}


  bool operator == (const Collector_Heartbeat_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Collector_Heartbeat_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_Heartbeat_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_Heartbeat_presult {
 public:


  virtual ~Collector_Heartbeat_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CollectorClient : virtual public CollectorIf {
 public:
  CollectorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  CollectorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Match(std::string& _return, const std::string& str_ad);
  void send_Match(const std::string& str_ad);
  void recv_Match(std::string& _return);
  void Heartbeat(const MachineInfo& info);
  void send_Heartbeat(const MachineInfo& info);
  void recv_Heartbeat();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CollectorProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<CollectorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CollectorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Match(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Heartbeat(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CollectorProcessor(boost::shared_ptr<CollectorIf> iface) :
    iface_(iface) {
    processMap_["Match"] = &CollectorProcessor::process_Match;
    processMap_["Heartbeat"] = &CollectorProcessor::process_Heartbeat;
  }

  virtual ~CollectorProcessor() {}
};

class CollectorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CollectorProcessorFactory(const ::boost::shared_ptr< CollectorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CollectorIfFactory > handlerFactory_;
};

class CollectorMultiface : virtual public CollectorIf {
 public:
  CollectorMultiface(std::vector<boost::shared_ptr<CollectorIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CollectorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CollectorIf> > ifaces_;
  CollectorMultiface() {}
  void add(boost::shared_ptr<CollectorIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Match(std::string& _return, const std::string& str_ad) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Match(_return, str_ad);
    }
    ifaces_[i]->Match(_return, str_ad);
    return;
  }

  void Heartbeat(const MachineInfo& info) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Heartbeat(info);
    }
    ifaces_[i]->Heartbeat(info);
  }

};



#endif
